<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Dawson Dobash" />

<meta name="date" content="2021-10-14" />

<title>Nausea/Body Temperature: Exploration</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { color: #cccccc; background-color: #303030; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ffcfaf; } /* Alert */
code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #dca3a3; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #f0dfaf; } /* ControlFlow */
code span.ch { color: #dca3a3; } /* Char */
code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code span.co { color: #7f9f7f; } /* Comment */
code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code span.do { color: #7f9f7f; } /* Documentation */
code span.dt { color: #dfdfbf; } /* DataType */
code span.dv { color: #dcdccc; } /* DecVal */
code span.er { color: #c3bf9f; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #c0bed1; } /* Float */
code span.fu { color: #efef8f; } /* Function */
code span.im { } /* Import */
code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
code span.kw { color: #f0dfaf; } /* Keyword */
code span.op { color: #f0efd0; } /* Operator */
code span.ot { color: #efef8f; } /* Other */
code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code span.sc { color: #dca3a3; } /* SpecialChar */
code span.ss { color: #cc9393; } /* SpecialString */
code span.st { color: #cc9393; } /* String */
code span.va { } /* Variable */
code span.vs { color: #cc9393; } /* VerbatimString */
code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Data Analysis Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="./aboutme.html">About Me</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./rcoding.html">R Coding</a>
    </li>
    <li>
      <a href="./visualization.html">Visualization</a>
    </li>
    <li>
      <a href="./tidytuesday.html">Tidy Tuesday Exercise</a>
    </li>
    <li>
      <a href="./tidytuesday2.html">Tidy Tuesday 2 Exercise</a>
    </li>
    <li>
      <a href="./exploration.html">Nausea/Body Temperature: Exploration</a>
    </li>
    <li>
      <a href="./analysisscript-rmd.html">Nausea/Body Temperature: Model Fitting using Tidymodels</a>
    </li>
    <li>
      <a href="./analysisscript_pt2.html">Nausea/Body Temperature: Cross-Validation, ROC-Auc, and RMSE</a>
    </li>
    <li>
      <a href="./analysisscript_pt3.html">Nausea/Body Temperature: Machine Learning Modeling</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/dawsond34/DawsonDobash-MADA-portfolio/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Nausea/Body Temperature: Exploration</h1>
<h4 class="author">Dawson Dobash</h4>
<h4 class="date">10/14/2021</h4>

</div>


<p>This is the exploratory analysis portion of the module-Fitting Basic Statistical Models.We will be looking at data from <a href="https://datadryad.org/stash/dataset/doi:10.5061/dryad.51c59zw4v">Brian McKay’s paper</a>. For our analysis, we are using body temperature as our continuous outcome and Nausea as our main categorical outcome. We will use the other variables within the data set to determine any correlations with the outcomes.</p>
<p>This exploration portion will include some summary statistics for continuous variables as well as histograms to show the distribution of continuous variables. Finally we will have some plots comparing two or more variables.</p>
<p>To find the full analysis on this data set, click on <a href="https://github.com/dawsond34/DawsonDobash-MADA-analysis3">this link</a> and it will take you to my github repository.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Reading in packages needed and the data set from using the here package</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --</code></pre>
<pre><code>## v readr   2.0.2     v forcats 0.5.1
## v stringr 1.4.0</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x rlang::%@%()         masks purrr::%@%()
## x rlang::as_function() masks purrr::as_function()
## x readr::col_factor()  masks scales::col_factor()
## x vctrs::data_frame()  masks tibble::data_frame(), dplyr::data_frame()
## x purrr::discard()     masks scales::discard()
## x Matrix::expand()     masks tidyr::expand()
## x dplyr::filter()      masks stats::filter()
## x stringr::fixed()     masks recipes::fixed()
## x rlang::flatten()     masks purrr::flatten()
## x rlang::flatten_chr() masks purrr::flatten_chr()
## x rlang::flatten_dbl() masks purrr::flatten_dbl()
## x rlang::flatten_int() masks purrr::flatten_int()
## x rlang::flatten_lgl() masks purrr::flatten_lgl()
## x rlang::flatten_raw() masks purrr::flatten_raw()
## x rlang::invoke()      masks purrr::invoke()
## x dplyr::lag()         masks stats::lag()
## x rlang::list_along()  masks purrr::list_along()
## x rlang::modify()      masks purrr::modify()
## x Matrix::pack()       masks tidyr::pack()
## x rlang::prepend()     masks purrr::prepend()
## x readr::spec()        masks yardstick::spec()
## x rlang::splice()      masks purrr::splice()
## x Matrix::unpack()     masks tidyr::unpack()</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;gtsummary&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:recipes&#39;:
## 
##     all_numeric</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;files&quot;</span> ,<span class="st">&quot;processeddata.rds&quot;</span>))</span></code></pre></div>
<p>Since there are a lot of variables to select for predicting body temperature and nausea, I will pick a couple that seem to be interesting or possibly somewhat related (at least I think). Below are the variables I will explore along with our main outcomes:</p>
<p><em>ChillsSweats</em>: Having Chills or Sweats (Yes or No) <br /> <em>SubjectiveFever</em>: If a person has a subjective fever (Yes or No) <br /> <em>Diarrhea</em>: Having diarrhea (Yes or no) <br /> <em>Insomnia</em>: Is the person experiencing sleeplessness (Yes or No) <br /> <em>MyalgiaYN</em>: If a person experiences myalgia (Yes or No)</p>
<div id="univariate-exploration" class="section level1">
<h1>Univariate Exploration</h1>
<div id="main-outcomes" class="section level3">
<h3>Main Outcomes</h3>
<p><br /> <strong>Body Temperature</strong></p>
<p>This is showing the summary statistics of the body temperature of each subject.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>BodyTemp)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   97.20   98.20   98.50   98.94   99.30  103.10</code></pre>
<p>We can see that the body temperatures ranges from 97.2 and 103.1 degrees Fahrenheit with a mean temperature of 98.94 and median of 98.5. The general standard temperature is supposed to be around 98.6 but, with recent studies it seems to be lower and within the low 98’s. Therefore, the 25% of people over a temperature of 99.3 might have some reasons on why their temperatures are so high.</p>
<p>Below is showing a histogram of body temperatures.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>BodyTemp)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 1: Histogram of Body Temperatures&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Body Temperature (in Fahrenheit)&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>plot1</span></code></pre></div>
<p><img src="exploration_files/figure-html/histogram%20of%20bodytemp-1.png" width="672" /></p>
<p>In this histogram, you can see that the temperatures are right skewed with most of the data is around 98 degrees. This is a similar result from the summary statistics as 75% of the data is under the temperature of 99.3.</p>
<p><br /> <strong>Nausea</strong></p>
<p>Here we are looking at the data frequency of those who have Nausea and those who dont. This is expressed through a bar chart as well.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(data<span class="sc">$</span>Nausea))</span></code></pre></div>
<pre><code>##  No Yes 
## 475 255</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(Nausea) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Nausea) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Nausea, <span class="at">y=</span>count)) <span class="sc">+</span><span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span><span class="fu">ggtitle</span>(<span class="st">&quot;Figure 2: Bar Chart of Nausea&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>plot2</span></code></pre></div>
<p><img src="exploration_files/figure-html/data%20frequency%20of%20nausea-1.png" width="672" /></p>
<p>We can see that there are double the amount of people who are not experiencing nausea.</p>
</div>
<div id="predictor-variables" class="section level3">
<h3>Predictor Variables</h3>
<p>This table is looking at all of the predictor variables where it is diplaying the counts of yes and the percent of the people who had a yes response.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(ChillsSweats, SubjectiveFever, Diarrhea, Insomnia, MyalgiaYN) <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tbl_summary</span>()</span></code></pre></div>
<div id="uywdwdhtad" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#uywdwdhtad .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#uywdwdhtad .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uywdwdhtad .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#uywdwdhtad .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#uywdwdhtad .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uywdwdhtad .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uywdwdhtad .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#uywdwdhtad .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#uywdwdhtad .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#uywdwdhtad .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#uywdwdhtad .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#uywdwdhtad .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#uywdwdhtad .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#uywdwdhtad .gt_from_md > :first-child {
  margin-top: 0;
}

#uywdwdhtad .gt_from_md > :last-child {
  margin-bottom: 0;
}

#uywdwdhtad .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#uywdwdhtad .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#uywdwdhtad .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uywdwdhtad .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#uywdwdhtad .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uywdwdhtad .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#uywdwdhtad .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#uywdwdhtad .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uywdwdhtad .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uywdwdhtad .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#uywdwdhtad .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uywdwdhtad .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#uywdwdhtad .gt_left {
  text-align: left;
}

#uywdwdhtad .gt_center {
  text-align: center;
}

#uywdwdhtad .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#uywdwdhtad .gt_font_normal {
  font-weight: normal;
}

#uywdwdhtad .gt_font_bold {
  font-weight: bold;
}

#uywdwdhtad .gt_font_italic {
  font-style: italic;
}

#uywdwdhtad .gt_super {
  font-size: 65%;
}

#uywdwdhtad .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 730</strong><sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Chills/Sweats</td>
<td class="gt_row gt_center">600 (82%)</td></tr>
    <tr><td class="gt_row gt_left">Subjective Fever</td>
<td class="gt_row gt_center">500 (68%)</td></tr>
    <tr><td class="gt_row gt_left">Diarrhea</td>
<td class="gt_row gt_center">99 (14%)</td></tr>
    <tr><td class="gt_row gt_left">Sleeplessness</td>
<td class="gt_row gt_center">415 (57%)</td></tr>
    <tr><td class="gt_row gt_left">Myalgia</td>
<td class="gt_row gt_center">651 (89%)</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="2">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          n (%)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>Of all of the predictor variables insomnia has the most even distribution. This could potentially mean that insomnia might not have an impact on our outcomes but we will have to see. We can also see that myalgia is the most one-sided predictor variable and we will see if that is due to some sort of association with either body temperature or nausea. All of these variables seem to have more yes values than no except the diarrhea variable.</p>
<p><br /></p>
</div>
</div>
<div id="bivariate-analysis" class="section level1">
<h1>Bivariate Analysis</h1>
<div id="body-temperature-vs.-predictor-variables" class="section level3">
<h3>Body Temperature vs. Predictor Variables</h3>
<p><strong>Body Temperature by Insomnia</strong></p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is a boxplot of body temperature by insomnia.  </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>BodyTemp, <span class="at">y=</span>Insomnia)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 3: Boxplot of Body Temperature by Insomnia&quot;</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>plot3</span></code></pre></div>
<p><img src="exploration_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>We can see that the distributions are relatively the same no matter if the person experience insomnia or not.</p>
<p><br /></p>
<p><strong>Body Temperature by Chill or Sweats</strong></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is a boxplot of body temperature by chills or sweats.</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>BodyTemp, <span class="at">y=</span>ChillsSweats)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 4: Boxplot of Body Temperature by Chill or Sweats&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Chills or Sweats&quot;</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>plot4</span></code></pre></div>
<p><img src="exploration_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>In this boxplot, we can see there is still definetly some overlap between the two groups but people who did not experience chills and sweats seem to be more on the lower end of the body temperatures compared to this who have experienced them. However it might look to seem that no significant difference is present based on the boxplots.</p>
<p><br /></p>
<p><strong>Body Temperature by Myalgia</strong></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is a boxplot of body temperature by myalgia (yes or no).</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>plot5 <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>BodyTemp, <span class="at">y=</span>MyalgiaYN)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 5: Boxplot of Body Temperature by Myalgia&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Myalgia&quot;</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plot5</span></code></pre></div>
<p><img src="exploration_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Similar to chills or sweats, myalgia seems to favor the lower end of body temperatures but still with overlap. The spread of observations is smaller for those who did not experience myalgia except the outliers present.</p>
</div>
<div id="nausea-vs.-prediction-variables" class="section level3">
<h3>Nausea vs. Prediction Variables</h3>
<p><strong>Nausea by Subjective Fever</strong></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is a stacked percentage bar plot of nausea by subjective fever. The way I did it was creating a count variable for the number of yes&#39;s and no&#39;s for nausea. This value will be used on the y-axis and turned into a percentage using the scales package.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>plot6 <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(Nausea, SubjectiveFever) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Nausea, SubjectiveFever) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Nausea, <span class="at">y=</span>count, <span class="at">fill=</span>SubjectiveFever)) <span class="sc">+</span>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="st">&quot;fill&quot;</span>, <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span>percent) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 6: Stacked Bar Chart of Nausea by Subjective Fever&quot;</span>) <span class="sc">+</span><span class="fu">ylab</span>(<span class="st">&quot;Percentage&quot;</span>) </span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Nausea&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>plot6</span></code></pre></div>
<p><img src="exploration_files/figure-html/unnamed-chunk-5-1.png" width="672" /> If we look at the stacked bar chart, we can see that there are more people who have a subjective fever when they are nauseated. Around 75% of people who are nauseated have subjective fevers compared to around 60% for not nauseated.</p>
<p><br /></p>
<p><strong>Nausea by Diarrhea</strong></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is a stacked percentage bar plot of nausea by diarrhea. The way I did it was creating a count variable for the number of yes&#39;s and no&#39;s for nausea. This value will be used on the y-axis and turned into a percentage using the scales package.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>plot7 <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(Nausea, Diarrhea) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Nausea, Diarrhea) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Nausea, <span class="at">y=</span>count, <span class="at">fill=</span>Diarrhea)) <span class="sc">+</span>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="st">&quot;fill&quot;</span>, <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span>percent) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 7: Stacked Bar Chart of Nausea by Diarrhea&quot;</span>) <span class="sc">+</span><span class="fu">ylab</span>(<span class="st">&quot;Percentage&quot;</span>) </span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Nausea&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>plot7</span></code></pre></div>
<p><img src="exploration_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>In figure 7, we can see that around 25% of people who are nauseated also have diarrhea compared to only 10% has diarrhea while not being nauseated.</p>
<p><br /></p>
<p><strong>Nausea by Myalgia</strong></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is a stacked percentage bar plot of nausea by myalgia. The way I did it was creating a count variable for the number of yes&#39;s and no&#39;s for nausea. This value will be used on the y-axis and turned into a percentage using the scales package.</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>plot8 <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(Nausea, MyalgiaYN) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Nausea, MyalgiaYN) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Nausea, <span class="at">y=</span>count, <span class="at">fill=</span>MyalgiaYN)) <span class="sc">+</span>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="st">&quot;fill&quot;</span>, <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span>percent) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 8: Stacked Bar Chart of Nausea by Myalgia&quot;</span>) <span class="sc">+</span><span class="fu">ylab</span>(<span class="st">&quot;Percentage&quot;</span>) </span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Nausea&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>plot8</span></code></pre></div>
<p><img src="exploration_files/figure-html/unnamed-chunk-7-1.png" width="672" /> We can see that for both those who arent and who are nauseated have relatively high percentage of those who experience Myalgia.</p>
<p><br /></p>
<p><strong>Nausea by Insomnia</strong></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is a stacked percentage bar plot of nausea by insomnia. The way I did it was creating a count variable for the number of yes&#39;s and no&#39;s for nausea. This value will be used on the y-axis and turned into a percentage using the scales package.</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>plot9 <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(Nausea, Insomnia) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Nausea, Insomnia) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Nausea, <span class="at">y=</span>count, <span class="at">fill=</span>Insomnia)) <span class="sc">+</span>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="st">&quot;fill&quot;</span>, <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span>percent) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 9: Stacked Bar Chart of Nausea by Insomnia&quot;</span>) <span class="sc">+</span><span class="fu">ylab</span>(<span class="st">&quot;Percentage&quot;</span>) </span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Nausea&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>plot9</span></code></pre></div>
<p><img src="exploration_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Finally just like the boxplot of body temperature and insomnia, insomnia shares a similar relationship whether or not the person is nauseated or not.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
