<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Tidy Tuesday 2</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { color: #cccccc; background-color: #303030; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ffcfaf; } /* Alert */
code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #dca3a3; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #f0dfaf; } /* ControlFlow */
code span.ch { color: #dca3a3; } /* Char */
code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code span.co { color: #7f9f7f; } /* Comment */
code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code span.do { color: #7f9f7f; } /* Documentation */
code span.dt { color: #dfdfbf; } /* DataType */
code span.dv { color: #dcdccc; } /* DecVal */
code span.er { color: #c3bf9f; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #c0bed1; } /* Float */
code span.fu { color: #efef8f; } /* Function */
code span.im { } /* Import */
code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
code span.kw { color: #f0dfaf; } /* Keyword */
code span.op { color: #f0efd0; } /* Operator */
code span.ot { color: #efef8f; } /* Other */
code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code span.sc { color: #dca3a3; } /* SpecialChar */
code span.ss { color: #cc9393; } /* SpecialString */
code span.st { color: #cc9393; } /* String */
code span.va { } /* Variable */
code span.vs { color: #cc9393; } /* VerbatimString */
code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Data Analysis Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="./aboutme.html">About Me</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./rcoding.html">R Coding</a>
    </li>
    <li>
      <a href="./visualization.html">Visualization</a>
    </li>
    <li>
      <a href="./tidytuesday.html">Tidy Tuesday Exercise</a>
    </li>
    <li>
      <a href="./tidytuesday2.html">Tidy Tuesday 2 Exercise</a>
    </li>
    <li>
      <a href="./exploration.html">Nausea/Body Temperature: Exploration</a>
    </li>
    <li>
      <a href="./analysisscript-rmd.html">Nausea/Body Temperature: Model Fitting using Tidymodels</a>
    </li>
    <li>
      <a href="./analysisscript_pt2.html">Nausea/Body Temperature: Cross-Validation, ROC-Auc, and RMSE</a>
    </li>
    <li>
      <a href="./analysisscript_pt3.html">Nausea/Body Temperature: Machine Learning Modeling</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/dawsond34/DawsonDobash-MADA-portfolio/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Tidy Tuesday 2</h1>

</div>


<p>This tidy tuesday exercise is looking at marble racing. Here is a link to the github repository to find the data as well as some more information about the marble racing. <a href="https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-06-02/readme.md" class="uri">https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-06-02/readme.md</a></p>
<p>Reading in packages.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;janitor&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     chisq.test, fisher.test</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)    <span class="co"># for classification and regression training</span></span></code></pre></div>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## 
## Attaching package: &#39;caret&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:yardstick&#39;:
## 
##     precision, recall, sensitivity, specificity</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     lift</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kernlab)  <span class="co"># for fitting SVMs</span></span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;kernlab&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     cross</code></pre>
<pre><code>## The following object is masked from &#39;package:scales&#39;:
## 
##     alpha</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     alpha</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vip)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;vip&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:utils&#39;:
## 
##     vi</code></pre>
<p>Reading in the data.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">34</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the Data</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>marbles <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-02/marbles.csv&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 256 Columns: 14</code></pre>
<pre><code>## -- Column specification --------------------------------------------------------
## Delimiter: &quot;,&quot;
## chr (9): date, race, site, source, marble_name, team_name, pole, host, notes
## dbl (5): time_s, points, track_length_m, number_laps, avg_time_lap</code></pre>
<pre><code>## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Or read in with tidytuesdayR package (https://github.com/thebioengineer/tidytuesdayR)</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Either ISO-8601 date or year/week works!</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co">#This will create copies of each dataset into my own folder for the online portfolio</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>marbles <span class="sc">%&gt;%</span> </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a> <span class="fu">write_csv</span>(<span class="st">&quot;data/tidy_tuesday/marbles.csv&quot;</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Looking at all of the details pertaining to the data set.</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>skimr<span class="sc">::</span><span class="fu">skim</span>(marbles)</span></code></pre></div>
<table>
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">marbles</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">256</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">14</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">9</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">date</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">8</td>
<td align="right">9</td>
<td align="right">0</td>
<td align="right">16</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">16</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">site</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">7</td>
<td align="right">15</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">source</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">34</td>
<td align="right">34</td>
<td align="right">0</td>
<td align="right">16</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">marble_name</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">9</td>
<td align="right">0</td>
<td align="right">32</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">team_name</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">6</td>
<td align="right">16</td>
<td align="right">0</td>
<td align="right">16</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">pole</td>
<td align="right">128</td>
<td align="right">0.50</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">16</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">host</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">notes</td>
<td align="right">249</td>
<td align="right">0.03</td>
<td align="right">37</td>
<td align="right">100</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">time_s</td>
<td align="right">3</td>
<td align="right">0.99</td>
<td align="right">190.84</td>
<td align="right">169.13</td>
<td align="right">17.76</td>
<td align="right">28.40</td>
<td align="right">36.28</td>
<td align="right">338.16</td>
<td align="right">492.01</td>
<td align="left">▇▁▁▇▁</td>
</tr>
<tr class="even">
<td align="left">points</td>
<td align="right">128</td>
<td align="right">0.50</td>
<td align="right">6.45</td>
<td align="right">7.74</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
<td align="right">3.00</td>
<td align="right">11.25</td>
<td align="right">26.00</td>
<td align="left">▇▂▂▁▁</td>
</tr>
<tr class="odd">
<td align="left">track_length_m</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">13.22</td>
<td align="right">0.95</td>
<td align="right">11.90</td>
<td align="right">12.62</td>
<td align="right">13.02</td>
<td align="right">14.13</td>
<td align="right">14.55</td>
<td align="left">▅▅▂▁▇</td>
</tr>
<tr class="even">
<td align="left">number_laps</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">6.25</td>
<td align="right">5.53</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">5.00</td>
<td align="right">10.25</td>
<td align="right">16.00</td>
<td align="left">▇▁▃▂▂</td>
</tr>
<tr class="odd">
<td align="left">avg_time_lap</td>
<td align="right">3</td>
<td align="right">0.99</td>
<td align="right">29.70</td>
<td align="right">5.55</td>
<td align="right">17.76</td>
<td align="right">25.94</td>
<td align="right">30.05</td>
<td align="right">33.65</td>
<td align="right">41.62</td>
<td align="left">▃▆▇▇▂</td>
</tr>
</tbody>
</table>
<p>Cleaning the data. I am making it more horizontal than vertical. I am creating variables for the different times (qualifying and races).</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Marbles2 is just removing some variables I do not want and then rearranging the data so I can make it horizontal</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>marbles2 <span class="ot">&lt;-</span> marbles <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>date, <span class="sc">-</span>source, <span class="sc">-</span>notes) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">type_of_race =</span> <span class="fu">ifelse</span>(<span class="fu">grepl</span>(<span class="st">&quot;Q&quot;</span>, race), <span class="st">&quot;qualifying&quot;</span>, <span class="st">&quot;race&quot;</span>),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                                                          <span class="at">qual_time =</span> <span class="fu">ifelse</span>(<span class="fu">grepl</span>(<span class="st">&quot;Q&quot;</span>, race), avg_time_lap, <span class="cn">NA</span>),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                                                          <span class="at">avg_race_time =</span> <span class="fu">ifelse</span>(<span class="fu">grepl</span>(<span class="st">&quot;R&quot;</span>, race), avg_time_lap, <span class="cn">NA</span>),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                                                          <span class="at">total_race_time =</span> <span class="fu">ifelse</span>(<span class="fu">grepl</span>(<span class="st">&quot;R&quot;</span>, race), time_s, <span class="cn">NA</span>))</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Splitting races from qualifiers. </span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>Qualify <span class="ot">&lt;-</span> marbles2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(type_of_race <span class="sc">==</span> <span class="st">&quot;qualifying&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(site, marble_name, qual_time)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>Race <span class="ot">&lt;-</span> marbles2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(type_of_race <span class="sc">==</span> <span class="st">&quot;race&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>pole, <span class="sc">-</span>type_of_race, <span class="sc">-</span>qual_time, <span class="sc">-</span>time_s, <span class="sc">-</span>avg_time_lap) </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Combining the two data sets again so it will be horizontal not vertical and combining them by the name of the marble</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>clean_data <span class="ot">=</span> <span class="fu">merge</span>(Race, Qualify,<span class="at">by=</span><span class="fu">c</span>(<span class="st">&quot;site&quot;</span>,<span class="st">&quot;marble_name&quot;</span>))</span></code></pre></div>
<div id="exploratory-analysis" class="section level1">
<h1>Exploratory Analysis</h1>
<p>Some things I want to check out and look at will be how many unique racers are there and how many times each one race in official races. I also want to check how their one lap qualifying lap compares to their actual average lap time. The final thing I want to check out is the total number of points each team earned and if there was some teams that either dominated or struggled compared to the others.</p>
<p>When looking at the number of unique marbles within the races, we can see that there are a total of 32 and each raced four times. I also grouped them by teams as well. This shows that there were two racers per team and they both raced 4 times each. This makes sense as there is a total of eight races within this data set. Therefore the two racers split races for the team.</p>
<p>Table 1</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating a table using the count function to count the number of marbles are displayed in the data specifically subsetted to only the offical races</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>clean_data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(team_name, marble_name) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Table 1: Number of races for each marble&quot;</span>)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;team_name&#39;. You can override using the `.groups` argument.</code></pre>
<pre><code>## $title
## # A tibble: 32 x 3
## # Groups:   team_name [16]
##    team_name      marble_name count
##    &lt;chr&gt;          &lt;chr&gt;       &lt;int&gt;
##  1 Balls of Chaos Anarchy         4
##  2 Balls of Chaos Clutter         4
##  3 Green Ducks    Billy           4
##  4 Green Ducks    Mallard         4
##  5 Hazers         Hazy            4
##  6 Hazers         Smoggy          4
##  7 Hornets        Hive            4
##  8 Hornets        Vespa           4
##  9 Limers         Limelime        4
## 10 Limers         Sublime         4
## # ... with 22 more rows
## 
## $subtitle
## [1] &quot;Table 1: Number of races for each marble&quot;
## 
## attr(,&quot;class&quot;)
## [1] &quot;labels&quot;</code></pre>
<p>Figure 1 shows 8 scatterplots displaying the qualifying times versus the average lap times for each race. We can see for most of the races that there is no association except for race 2 and somewhat of race 8.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating scatterplots for each race and comparing the qualifying time to the average race time</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(race<span class="sc">==</span><span class="st">&quot;S1R1&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>qual_time, <span class="at">y=</span>avg_race_time)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Race 1&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Qualifying time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Average lap time&quot;</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(race<span class="sc">==</span><span class="st">&quot;S1R2&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>qual_time, <span class="at">y=</span>avg_race_time)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Race 2&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Qualifying time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Average lap time&quot;</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(race<span class="sc">==</span><span class="st">&quot;S1R3&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>qual_time, <span class="at">y=</span>avg_race_time)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Race 3&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Qualifying time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Average lap time&quot;</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(race<span class="sc">==</span><span class="st">&quot;S1R4&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>qual_time, <span class="at">y=</span>avg_race_time)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Race 4&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Qualifying time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Average lap time&quot;</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>plot5 <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(race<span class="sc">==</span><span class="st">&quot;S1R5&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>qual_time, <span class="at">y=</span>avg_race_time)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Race 5&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Qualifying time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Average lap time&quot;</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>plot6 <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(race<span class="sc">==</span><span class="st">&quot;S1R6&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>qual_time, <span class="at">y=</span>avg_race_time)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Race 6&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Qualifying time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Average lap time&quot;</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>plot7 <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(race<span class="sc">==</span><span class="st">&quot;S1R7&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>qual_time, <span class="at">y=</span>avg_race_time)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Race 7&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Qualifying time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Average lap time&quot;</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>plot8 <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(race<span class="sc">==</span><span class="st">&quot;S1R8&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>qual_time, <span class="at">y=</span>avg_race_time)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Race 8&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Qualifying time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Average lap time&quot;</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Joining all of the plots into one large plot</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>joint <span class="ot">=</span> <span class="fu">ggarrange</span>(plot1,plot2,plot3,plot4,plot5,plot6,plot7,plot8, <span class="at">ncol=</span><span class="dv">4</span>, <span class="at">nrow=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).

## Warning: Removed 1 rows containing missing values (geom_point).

## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(joint, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">&quot;Figure 1: Scatterplots of all the races comparing </span><span class="sc">\n</span><span class="st"> the average race time and the qualified time&quot;</span>, <span class="at">size =</span> <span class="dv">15</span>))</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>From table 2 we can see that the Savage Speeders and Hazers dominated the rest of the teams in terms of total points earned throughout the season.</p>
<p>Table 2</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating a table to show the teams overall season points</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>clean_data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(team_name) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">total_points =</span> <span class="fu">sum</span>(points)) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(total_points)) <span class="sc">%&gt;%</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Table 2: Total points for each team for this season of racing&quot;</span>)</span></code></pre></div>
<pre><code>## $title
## # A tibble: 16 x 2
##    team_name        total_points
##    &lt;chr&gt;                   &lt;dbl&gt;
##  1 Savage Speeders           101
##  2 Hazers                     94
##  3 O&#39;rangers                  69
##  4 Snowballs                  66
##  5 Green Ducks                64
##  6 Team Galactic              64
##  7 Team Primary               54
##  8 Team Momo                  49
##  9 Thunderbolts               49
## 10 Balls of Chaos             46
## 11 Mellow Yellow              44
## 12 Midnight Wisps             34
## 13 Rojo Rollers               32
## 14 Raspberry Racers           27
## 15 Limers                     25
## 16 Hornets                     8
## 
## $subtitle
## [1] &quot;Table 2: Total points for each team for this season of racing&quot;
## 
## attr(,&quot;class&quot;)
## [1] &quot;labels&quot;</code></pre>
<p>Looking at this data, we have eight different races with each track having its own specifications such as length of track and laps. I want to standardize this in some way. Following Randy Olsen’s way of standardizing found in <a href="http://www.randalolson.com/2020/05/24/a-data-driven-look-at-marble-racing/">this</a> article, I will use the similar approach. This approach will be dividing the marbles individual race times with the average race time for each racer for each race. This will act as my outcome. I want to use the team name as my main predictor to see if one team has overall faster marbles (this is kind of funny to think about. We can think of if a marble is more smooth and has no scratches on it so it goes faster or if there are different sized marbles that could also factor in). One thing that could show up is having two different ‘populations’ within the team as one marble could be very slow and the other marble on the team is really fast. Therefore I will run one more exploratory analysis to see if there is a difference. I will also include the variables standard qualifying time (which is the same idea as the standard race time), host, and site as other predictor variables.</p>
<p>From Figure 2, we can see that there is some variability between the teams and some of these are significantly different than the others. In reality they all should be the same as all of the marbles are supposed to be the same and no distictions should be present but this boxplot tells different.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the average race time and qualifying times using the summarise function</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>mean_time <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(race) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean_racetime =</span> <span class="fu">mean</span>(total_race_time, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                                                         <span class="at">mean_qualtime =</span> <span class="fu">mean</span>(qual_time, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating multiples for each time to be able to line them up in the data set</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>mean_time <span class="ot">&lt;-</span> mean_time[<span class="fu">rep</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(mean_time)), <span class="at">each =</span> <span class="dv">16</span>), ] <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(race) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>race)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Arranging the data set so I can line up the observations for both data sets</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>clean_data <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(race) </span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Combining the two data sets and creating the standard times for both the races and qualifying times </span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">cbind</span>(clean_data,mean_time) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">stand_race_time =</span> total_race_time<span class="sc">/</span>mean_racetime,</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>                                                          <span class="at">stand_qual_time =</span> qual_time<span class="sc">/</span>mean_qualtime) </span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.))</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the side by side boxplots to show the difference in the standard race times</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>team_name, <span class="at">y=</span>stand_race_time)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 2: Side-by-side boxplots showing the standard race times by team&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Team&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Standard Race Time&quot;</span>)</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>I will also create a test/training data sets.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is splitting the data using a proportion of 1/4 test and 3/4 training</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>split_data <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(data, <span class="at">prop =</span> <span class="dv">3</span><span class="sc">/</span><span class="dv">4</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#This is assigning acutal data sets to the ones that were made</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>training <span class="ot">&lt;-</span> <span class="fu">training</span>(split_data)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>test  <span class="ot">&lt;-</span> <span class="fu">testing</span>(split_data)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a cross-validation 5-fold</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>cvfold_data <span class="ot">=</span> <span class="fu">vfold_cv</span>(training, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">strata =</span> stand_race_time)</span></code></pre></div>
<p>Next I will create run a recipe for the full model and a recipe for the null model. From the null model, the rmse values are very low which could mean the is not too much variability between the values of the standard race times than I thought. The values are 0.0113 and 0.0113 for the training and test data set, respectfully.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Setting the linear model type</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="fu">set_engine</span>(<span class="st">&quot;lm&quot;</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co">#This is creating the full model recipe</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>stand_race_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(stand_race_time <span class="sc">~</span> team_name <span class="sc">+</span> site <span class="sc">+</span> stand_qual_time <span class="sc">+</span> host, <span class="at">data=</span> training) <span class="sc">%&gt;%</span> <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>())</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co">#This is creating the null model recipe</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>nulltrain_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(stand_race_time <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> training) <span class="sc">%&gt;%</span> <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>())</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co">#A workflow and fitted object is created for the null model</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>nulltrain_wrkflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(lm_mod) <span class="sc">%&gt;%</span> <span class="fu">add_recipe</span>(nulltrain_rec)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>nulltrain_fit <span class="ot">&lt;-</span> nulltrain_wrkflow <span class="sc">%&gt;%</span> <span class="fu">fit</span>(<span class="at">data=</span>training) </span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co">#We are augmenting for both the train and test data and then finding each rmse </span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(nulltrain_fit, training) <span class="sc">%&gt;%</span> <span class="fu">rmse</span>(<span class="at">truth =</span> stand_race_time, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard      0.0113</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(nulltrain_fit, test) <span class="sc">%&gt;%</span> <span class="fu">rmse</span>(<span class="at">truth =</span> stand_race_time, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard      0.0113</code></pre>
</div>
<div id="fitting-a-tree" class="section level1">
<h1>Fitting a tree</h1>
<p>The first type of ML tuning I am using is a simple tree. For this tree, we need to have multiple components. The first is specifying the specific type of model to use. This code below is creating the tree model and to look at a regression type of outcome.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the tree specification for a regression type of outcome</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>tune_spec <span class="ot">&lt;-</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">decision_tree</span>(</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cost_complexity =</span> <span class="fu">tune</span>(),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">tree_depth =</span> <span class="fu">tune</span>()</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;rpart&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a tree grid</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>tree_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(<span class="fu">cost_complexity</span>(),</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">tree_depth</span>(),</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">levels =</span> <span class="dv">5</span>)</span></code></pre></div>
<p>The next part is to create a workflow for the tree modeling. The model is the specification created above and the recipe is our full model recipe for the standard race time. Next we will apply our cross-validation 5-fold data in terms of tuning with a grid. This will create multiple models that will hopefully find a better model than the null model.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Making a wirkflow for the tree models. This uses the tuning specification above as the model type and the full model for standard race time as the recipe</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>tree_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(tune_spec) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(stand_race_rec)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co">#We re resampling the tree workflow by using the tune grid function and our cross-validation 5-fold data</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>tree_res <span class="ot">&lt;-</span> </span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  tree_wf <span class="sc">%&gt;%</span> </span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> cvfold_data,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">grid =</span> tree_grid</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<p>Now that we have created our tree, we can look at the results. The first plot shows the different models tested and their respected rmse values. The next table is showing which model between the different trees performed the best in terms of the lowest rmse which results in model 1.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The autoplot function shows basically the process of the tuning process</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>tree_res <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 3: Process of tuning for the tree model&quot;</span>)</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/evaluation%20tree-1.png" width="672" /></p>
<p>Table 3</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#selecting the best tree with the lowest rmse</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>best_tree <span class="ot">&lt;-</span> tree_res <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="st">&quot;rmse&quot;</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>best_tree</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   cost_complexity tree_depth .config              
##             &lt;dbl&gt;      &lt;int&gt; &lt;chr&gt;                
## 1    0.0000000001          1 Preprocessor1_Model01</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#putting in the best tree found into its own workflow</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>final_wf_tree <span class="ot">&lt;-</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  tree_wf <span class="sc">%&gt;%</span> </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(best_tree)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="co">#fitting the tree data into a fit object</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>tree_fit <span class="ot">&lt;-</span> final_wf_tree <span class="sc">%&gt;%</span> <span class="fu">fit</span>(<span class="at">data=</span>training)</span></code></pre></div>
<p>We plotted what the actual tree looks like. We also plotted a scatterplot of the predicted values versus the actual values, and a residual plot for this model. We can see that this tree does not really have a good fit as the values only are on two discrete predicted values and this also shows on the residual plot as well.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This displays the tree</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(<span class="fu">extract_fit_parsnip</span>(tree_fit)<span class="sc">$</span>fit, <span class="at">roundint=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/fitting%20plots%20tree-1.png" width="672" /></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We are augenting the tree fit object with the train data to help produce a mean rmse</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>aug_tree <span class="ot">&lt;-</span> <span class="fu">augment</span>(tree_fit, training) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">residual =</span> stand_race_time <span class="sc">-</span> .pred)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co">#This is a scatterplot showing the predicted values versus the actual values of body temperature</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>tree_predvsobs_plot <span class="ot">&lt;-</span> aug_tree <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>stand_race_time, <span class="at">y=</span>.pred)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 4: scatterplot of predicted values versus the observed values of </span><span class="sc">\n</span><span class="st"> standard race times with a reference line showing exact prediction </span><span class="sc">\n</span><span class="st"> (for Tree model)&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Standard Race Time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Predicted values&quot;</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>tree_predvsobs_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/fitting%20plots%20tree-2.png" width="672" /></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is showing the residual plot </span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>tree_resid_plot <span class="ot">&lt;-</span> aug_tree <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>.pred, <span class="at">y=</span>residual)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 5: residual plot for Tree model&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>tree_resid_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/fitting%20plots%20tree-3.png" width="672" /></p>
<p>In Table 4, this compares the two RMSE’s for the best model (model 1) from tree modeling and then for the null model. We can see that the RMSE is smaller but it is not big of a difference. However I guess relatively it is pretty different.</p>
<p>Table 4</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#comparing the tree models with the null model </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>tree_res <span class="sc">%&gt;%</span> <span class="fu">show_best</span>(<span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Warning: No value of `metric` was given; metric &#39;rmse&#39; will be used.</code></pre>
<pre><code>## # A tibble: 1 x 8
##   cost_complexity tree_depth .metric .estimator   mean     n  std_err .config   
##             &lt;dbl&gt;      &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;     
## 1    0.0000000001          1 rmse    standard   0.0104    25 0.000276 Preproces~</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(nulltrain_fit, training) <span class="sc">%&gt;%</span> <span class="fu">rmse</span>(<span class="at">truth =</span> stand_race_time, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard      0.0113</code></pre>
</div>
<div id="fitting-a-lasso-model" class="section level1">
<h1>Fitting a LASSO Model</h1>
<p>The next type of model we will be using is the LASSO model. It has a similar set up to the tree as we set a specific model type and then use it in a workflow for LASSO. The recipe is the same full model for standard race times.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the lasso model type. This uses the glmnet engine</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>lasso_mod <span class="ot">&lt;-</span> </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>(<span class="at">penalty =</span> <span class="fu">tune</span>(), <span class="at">mixture =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;glmnet&quot;</span>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co">#We are setting the LASSO workflow which similar to the tree, it uses the full model for the recipe and then the specific LASSO model I just made</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>lasso_workflow <span class="ot">&lt;-</span> </span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lasso_mod) <span class="sc">%&gt;%</span> </span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(stand_race_rec)</span></code></pre></div>
<p>We need to create a grid for tuning again using the cross-validation 5-fold data. This will eventually create multiple LASSO models to compare and find the best performing one by rmse.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a grid for the LASSO</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>lasso_reg_grid <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">penalty =</span> <span class="dv">10</span><span class="sc">^</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">30</span>))</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Using tune grid to help create the tuning process using the cross-validation 5-fold</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>lasso_res <span class="ot">&lt;-</span> </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  lasso_workflow <span class="sc">%&gt;%</span> </span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(cvfold_data,</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">grid =</span> lasso_reg_grid,</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">control =</span> <span class="fu">control_grid</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>),</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse))</span></code></pre></div>
<p>Figure 6 shows the transition from the tuning to finding the model with the lowest rmse and we see that the model with the lowest rmse is model 12 in Table 5. This was selected by the select_best function and specifying it to looking at rmse. We then used this best model into a new workflow which will be used to create a fit object to show the value of rmse.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The autoplot function shows basically the process of the tuning process</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>lasso_res <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 6: Display of the model selection process </span><span class="sc">\n</span><span class="st"> and its respected RMSE values&quot;</span>)</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/evaluation%20LASSO-1.png" width="672" /></p>
<p>Table 5</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is finding the best model with the lowest rmse</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>lasso_best <span class="ot">&lt;-</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  lasso_res <span class="sc">%&gt;%</span> </span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">show_best</span>(<span class="st">&quot;rmse&quot;</span>, <span class="at">n=</span><span class="dv">1</span>)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>lasso_best</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   penalty .metric .estimator   mean     n  std_err .config              
##     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;                
## 1 0.00137 rmse    standard   0.0105    25 0.000286 Preprocessor1_Model12</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating a workflow that only included the best model</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>final_wf_lasso <span class="ot">&lt;-</span> </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  lasso_workflow <span class="sc">%&gt;%</span> </span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(lasso_best)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a fit object to help show the predictions of each standard race time</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>lasso_fit <span class="ot">&lt;-</span> final_wf_lasso <span class="sc">%&gt;%</span> <span class="fu">fit</span>(<span class="at">data=</span>training)</span></code></pre></div>
<p>Figures 7 and 8 show the predicted values versus actual values and the the residual plot. From Figure 7, we can see a better plot than the tree one as there is no discrete values but it is still not getting the whole trend down. With the line being the slope of 1, this would be the exact prediction of a standard race time, there is still some spread of the data and one could say there is a slight trend upward but at the same time another could say there is no trend at all between the predicted and actual values. This can also be seen by Figure 8 as the points are still spread apart.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the residuals and displaying the scatterplot of the predicted values to the observed values of body temp using LASSO</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>aug_lasso <span class="ot">&lt;-</span> <span class="fu">augment</span>(lasso_fit, training) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">residual =</span> stand_race_time <span class="sc">-</span> .pred)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>lasso_predvsobs_plot <span class="ot">&lt;-</span> aug_lasso <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>stand_race_time, <span class="at">y=</span>.pred)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 7: scatterplot of predicted values versus the observed values </span><span class="sc">\n</span><span class="st"> of the standard race times with a reference line showing exact prediction </span><span class="sc">\n</span><span class="st"> (for LASSO model)&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Standard Race Time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Predicted values&quot;</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>lasso_predvsobs_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/fitting%20plots%20LASSO-1.png" width="672" /></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Residual plot</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>lasso_resid_plot <span class="ot">&lt;-</span> aug_lasso <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>.pred, <span class="at">y=</span>residual)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 8: residual plot for LASSO model&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>lasso_resid_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/fitting%20plots%20LASSO-2.png" width="672" /></p>
<p>To compare the best LASSO model to the null model, we can see the mean rmse is smaller than the null rmse, 0.0105 and 0.0113, respectively. This value of the rmse for the LASSO model is roughly the same as the simple tree model. Since the tree model is more simpler, for now I would choose that model over LASSO. But I will test two more different models.</p>
<p>Table 6</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#comparing the rmse from the LASSO model to the null model</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>lasso_res <span class="sc">%&gt;%</span> <span class="fu">show_best</span>(<span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   penalty .metric .estimator   mean     n  std_err .config              
##     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;                
## 1 0.00137 rmse    standard   0.0105    25 0.000286 Preprocessor1_Model12</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(nulltrain_fit, training) <span class="sc">%&gt;%</span> <span class="fu">rmse</span>(<span class="at">truth =</span> stand_race_time, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard      0.0113</code></pre>
</div>
<div id="random-forest" class="section level1">
<h1>Random Forest</h1>
<p>The next type of model is the random forest approach. Just like the other two models, we have to start with a model type specific to random forest for a regression outcome and apply it to a workflow. This workflow will be used to create a tuning grid that will create multiple models to find the best performing one.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>()</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the random forest model and specifying regression as the mode</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>rf_mod <span class="ot">&lt;-</span> </span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rand_forest</span>(<span class="at">mtry =</span> <span class="fu">tune</span>(), <span class="at">min_n =</span> <span class="fu">tune</span>(), <span class="at">trees =</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;ranger&quot;</span>, <span class="at">num.threads =</span> cores, <span class="at">importance =</span> <span class="st">&quot;permutation&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="co">#creating the workflow using the random forest model as our model and once again using the full model as our recipe</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>rf_workflow <span class="ot">&lt;-</span> </span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(rf_mod) <span class="sc">%&gt;%</span> </span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(stand_race_rec)</span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the tune grid for random forest using the cross-validation 5-fold</span></span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a>rf_res <span class="ot">&lt;-</span> </span>
<span id="cb63-17"><a href="#cb63-17" aria-hidden="true" tabindex="-1"></a>  rf_workflow <span class="sc">%&gt;%</span> </span>
<span id="cb63-18"><a href="#cb63-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(cvfold_data,</span>
<span id="cb63-19"><a href="#cb63-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">grid =</span> <span class="dv">25</span>,</span>
<span id="cb63-20"><a href="#cb63-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">control =</span> <span class="fu">control_grid</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>),</span>
<span id="cb63-21"><a href="#cb63-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse))</span></code></pre></div>
<pre><code>## i Creating pre-processing data to finalize unknown parameter: mtry</code></pre>
<p>Figure 9 shows some of the processes from tuning the random forest models. Table 7 shows which model is the best model created by the random forest process. We can see that model 5 is the best. This was selected by the select_best function and specifying it to looking at rmse. We then used this best model into a new workflow which will be used to create a fit object to show the value of rmse.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The autoplot function shows basically the process of the tuning process</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>rf_res <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 9: Tuning process for the random forest modeling&quot;</span>)</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/evaluation%20rf-1.png" width="672" /></p>
<p>Table 7</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is finding the best model with the lowest rmse</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>rf_best <span class="ot">&lt;-</span> </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  rf_res <span class="sc">%&gt;%</span> </span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="at">metric =</span> <span class="st">&quot;rmse&quot;</span>)</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>rf_best</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##    mtry min_n .config              
##   &lt;int&gt; &lt;int&gt; &lt;chr&gt;                
## 1     8    35 Preprocessor1_Model16</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">#making a workflow that only contains the best model</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>final_wf_rf <span class="ot">&lt;-</span> </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  rf_workflow <span class="sc">%&gt;%</span> </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(rf_best)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating a fit object to eventually use to find the rmse value and other predicted values for each standard race time </span></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>rf_fit <span class="ot">&lt;-</span> final_wf_rf <span class="sc">%&gt;%</span> <span class="fu">fit</span>(<span class="at">data=</span>training)</span></code></pre></div>
<p>Figure 10 and 11 show the predicted values versus actual values plot as well as the residual plot. We can see that Figure 10 is slightly better than the LASSO model and if we look specifically at the residual plot, it looks like the residuals are smaller. Most of the data is caught by the model and is more lined up around that slope of value 1 at least compared to the other models. There is still a slight increase in the residuals as the predicted values go up.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating residuals</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>aug_rf <span class="ot">&lt;-</span> <span class="fu">augment</span>(rf_fit, training) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">residual =</span> stand_race_time <span class="sc">-</span> .pred)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="co">#fitting a predicted versus actual values plot for random forest</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>rf_predvsobs_plot <span class="ot">&lt;-</span> aug_rf <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>stand_race_time, <span class="at">y=</span>.pred)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>)  <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 10: scatterplot of predicted values versus the observed values </span><span class="sc">\n</span><span class="st"> of standard race times with a reference line showing exact prediction </span><span class="sc">\n</span><span class="st"> (for Random Forest model)&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Standard Race Time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Predicted values&quot;</span>)</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>rf_predvsobs_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/fititng%20plots%20rf-1.png" width="672" /></p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co">#residual plot</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>rf_resid_plot <span class="ot">&lt;-</span> aug_rf <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>.pred, <span class="at">y=</span>residual)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 11: residual plot for Random Forest model&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>rf_resid_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/fititng%20plots%20rf-2.png" width="672" /></p>
<p>If we compare the mean rmse from the random forest modeling to the null, we can see that the rmse for the random forest is a lot smaller than the null, 0.0100 compared to 0.0113. Comparing the random forest RMSE to the other models, this RMSE is a lot better and I would prefer this model over LASSO and tree models.</p>
<p>Table 8</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co">#comparing the rmse from random forest to the null model</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>rf_res <span class="sc">%&gt;%</span> <span class="fu">show_best</span>(<span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 8
##    mtry min_n .metric .estimator   mean     n  std_err .config              
##   &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;                
## 1     8    35 rmse    standard   0.0100    25 0.000248 Preprocessor1_Model16</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(nulltrain_fit, training) <span class="sc">%&gt;%</span> <span class="fu">rmse</span>(<span class="at">truth =</span> stand_race_time, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard      0.0113</code></pre>
</div>
<div id="support-vector-machines-svm-models" class="section level1">
<h1>Support Vector Machines (SVM) models</h1>
<p>The last type of model we will be trying out is the support vector machine model. This svm model has a specific type of model needed to run the workflow. This specification and out full model for standard race time will create the workflow which will be used to create the many models from the tune grid.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the specification for the model type for SVM (for regression)</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>svm_spec <span class="ot">&lt;-</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svm_linear</span>(<span class="at">cost =</span> <span class="fu">tune</span>(), <span class="at">margin =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;kernlab&quot;</span>)</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating a workflow using the svm specification and our full model</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>svm_wflow <span class="ot">&lt;-</span> </span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(svm_spec) <span class="sc">%&gt;%</span> </span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(stand_race_rec)</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating multiple models using a tune grid </span></span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>svm_res <span class="ot">&lt;-</span> </span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>  svm_wflow <span class="sc">%&gt;%</span> </span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(cvfold_data,</span>
<span id="cb75-17"><a href="#cb75-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">grid =</span> <span class="dv">25</span>,</span>
<span id="cb75-18"><a href="#cb75-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">control =</span> <span class="fu">control_grid</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>),</span>
<span id="cb75-19"><a href="#cb75-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse))</span></code></pre></div>
<p>Figure 12 shows the tuning process for the SVM modeling along with each models respected RMSE.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The autoplot function shows basically the process of the tuning process</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>svm_res <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 12: Tuning process for the SVM modeling&quot;</span>)</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/evaluation%20Svm-1.png" width="672" /></p>
<p>Table 9 shows the best performing model based on the SVM modeling type. We can see that model 21 is the best.</p>
<p>Table 9</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is finding the best model with the lowest rmse</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>svm_best <span class="ot">&lt;-</span> </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  svm_res <span class="sc">%&gt;%</span> </span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="at">metric =</span> <span class="st">&quot;rmse&quot;</span>)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>svm_best</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##      cost   margin .config              
##     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                
## 1 0.00456 0.000594 Preprocessor1_Model09</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#making a workflow that only contains the best model</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>final_wf_svm <span class="ot">&lt;-</span> </span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  svm_wflow <span class="sc">%&gt;%</span> </span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(svm_best)</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating a fit object to eventually use to find the rmse value and other predicted values for each standard race time</span></span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>svm_fit <span class="ot">&lt;-</span> final_wf_svm <span class="sc">%&gt;%</span> <span class="fu">fit</span>(<span class="at">data=</span>training)</span></code></pre></div>
<pre><code>##  Setting default kernel parameters</code></pre>
<p>Figure 13 and 14 display the predicted values versus actual values as well as the residual plot. These two plots look very similar to the LASSO model. The model does not fit the trend/direction of the data but it is still better than the tree model.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating residuals</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>aug_svm <span class="ot">&lt;-</span> <span class="fu">augment</span>(svm_fit, training) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">residual =</span> stand_race_time <span class="sc">-</span> .pred)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="co">#fitting a predicted versus actual values plot for random forest</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>svm_predvsobs_plot <span class="ot">&lt;-</span> aug_svm <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>stand_race_time, <span class="at">y=</span>.pred)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>)  <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 13: scatterplot of predicted values versus the observed values </span><span class="sc">\n</span><span class="st"> of standard race times with a reference line showing exact prediction </span><span class="sc">\n</span><span class="st"> (for Support Vector Machines)&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Standard Race Time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Predicted values&quot;</span>)</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>svm_predvsobs_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/fititng%20plots%20svm-1.png" width="672" /></p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co">#residual plot</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>svm_resid_plot <span class="ot">&lt;-</span> aug_svm <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>.pred, <span class="at">y=</span>residual)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 14: residual plot for Support Vector Machines&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>svm_resid_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/fititng%20plots%20svm-2.png" width="672" /></p>
<p>If we look at Table 10, we can see that the two values of RMSE are not too different. The SVM model is still better but not as good as the random forest. The svm model produces a RMSE of 0.0109 while the null model has a RMSE of 0.0113.</p>
<p>Table 10</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co">#comparing the rmse from random forest to the null model</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>svm_res <span class="sc">%&gt;%</span> <span class="fu">show_best</span>(<span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 8
##      cost   margin .metric .estimator   mean     n  std_err .config             
##     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;               
## 1 0.00456 0.000594 rmse    standard   0.0109    25 0.000236 Preprocessor1_Model~</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(nulltrain_fit, training) <span class="sc">%&gt;%</span> <span class="fu">rmse</span>(<span class="at">truth =</span> stand_race_time, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard      0.0113</code></pre>
</div>
<div id="model-selection" class="section level1">
<h1>Model Selection</h1>
<p>From comparing all of the models, I am going to pick the random forest model as my best model to use for this data. Although it is the most complicated, the difference between the RMSE values of the random forest compared to the other is no match. This can be displayed by the predicted versus actual values plot (Figure 10) and residual plot (Figure 11). This model fits the data the best in terms of trend and direction as well. It is still slightly not aligned for hte residuals but it is better than the others</p>
<p>Now that I have picked the model, I will display the most important predictors within Figure 15. We can see that the marbles standard qualifying time does have a very high impact on how well they do in the race. We can also see that some teams did were important as well in determining the standard race times for each marble specifically from the team Savage Speeders and Limers.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co">#pull out the fit object</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> rf_fit<span class="sc">$</span>fit<span class="sc">$</span>fit<span class="sc">$</span>fit</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot variable importance</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>vip<span class="sc">::</span><span class="fu">vip</span>(x, <span class="at">num_features =</span> <span class="dv">10</span>)  <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 15: Display of the most important factors </span><span class="sc">\n</span><span class="st"> in predicting the marbles standard race time&quot;</span>)</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>To see how it compares to the test data set, we will run a few code blocks to see how well the RMSE is for the test data. If the values are close, then the random forest model did not overfit the training data and is a good fit for both.</p>
<p>If we look at Table 11, we can see that the two values for the test and training data, 0.0105 and 0.0100 respectively, are pretty close to each other. I dont think the model overfit the training data that much here as they are both still below the null model RMSE.</p>
<p>For Figures 16, we can see that it is a little hard to see what the trend is but within Figure 17 that most of it is uniformly around the 0 value and it has slightly higher residuals than the training data show (Figure 11)</p>
<p>Table 11</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>rf_test_fit <span class="ot">&lt;-</span> final_wf_rf <span class="sc">%&gt;%</span> <span class="fu">last_fit</span>(<span class="at">split=</span>split_data, <span class="at">metrics=</span><span class="fu">metric_set</span>(rmse))</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Comparing my test data rmse to the other best model data</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>rf_test_fit <span class="sc">%&gt;%</span> </span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   .metric .estimator .estimate .config             
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;               
## 1 rmse    standard      0.0105 Preprocessor1_Model1</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>rf_res <span class="sc">%&gt;%</span> <span class="fu">show_best</span>(<span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 8
##    mtry min_n .metric .estimator   mean     n  std_err .config              
##   &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;                
## 1     8    35 rmse    standard   0.0100    25 0.000248 Preprocessor1_Model16</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the augment to show the predicted values for each observation</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>rf_test_res <span class="ot">&lt;-</span> rf_test_fit <span class="sc">%&gt;%</span> <span class="fu">augment</span>()</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Scatterplot for predicted versus actual values</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>rf_predvsobs_test_plot <span class="ot">&lt;-</span> rf_test_res <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>stand_race_time, <span class="at">y=</span>.pred)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Figure 16: scatterplot of predicted values versus the observed values </span><span class="sc">\n</span><span class="st"> of standard race times with a reference line showing exact prediction </span><span class="sc">\n</span><span class="st"> (for SVM model using test data)&quot;</span>)  <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Standard Race Time&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Predicted values&quot;</span>)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>rf_predvsobs_test_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/final%20model%20analysis%20rf-1.png" width="672" /></p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Residual plot</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>rf_resid_test_plot <span class="ot">&lt;-</span> rf_test_res <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>.pred, <span class="at">y=</span>.resid)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Fgiure 17: residual plot for SVM model </span><span class="sc">\n</span><span class="st"> (using test data)&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>rf_resid_test_plot</span></code></pre></div>
<p><img src="tidytuesday2_files/figure-html/final%20model%20analysis%20rf-2.png" width="672" /></p>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<p>In this exercise, we were presented with marble racing data for eight different race. I tested out four different machine learning models to this data in which they include: Tree modeling, LASSO modeling, Random Forest modeling, and Support Vector Machines modeling. From these four models, I test out the performance of them using the statistic RMSE. I tested out my full model, which included the predictors team name, standard qualifying time, site, and host of the race, to a null model. All of the machine learning models were better performing than the null model. The best performing model was the random forest model. With the title of best performing and some other factors, I decided I will use the random forest model. The last part of my test was to make sure my results from using training data to create the model is similar to the results I would get from using the test data. The RMSE’s were similar which means no over fitting by the model to the training data and it genuinely is a good model for the data. We also found out that the most important predictor for predicting the standard race times were the standard qualifying times. This means those who had good qualifying time also had a good race time.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
